using System.Globalization;
using Typewriter.Abstractions;
using Typewriter.Engine;
using Typewriter.Roslyn;
using Xunit;

namespace Typewriter.SnapshotTests;

public sealed class ExternalRecipeSnapshotTests
{
    [Theory]
    [InlineData(
        data: ["Angular/System.Text.Json/services/_AutogeneratedServices.tst", "angular-system-text-json/services", false])]
    [InlineData(
        data: ["Angular/System.Text.Json/models/_AutogeneratedModels.tst", "angular-system-text-json/models", false])]
    [InlineData(
        data: ["Angular/Newtonsoft.Json/models/_AutogeneratedModels.tst", "angular-newtonsoft-json/models", false])]
    [InlineData(
        data: ["src/AngularWebApiSample/ClientApp/apps/client-app/src/api/constants/_AutogeneratedModels.tst", "angular-sample-src/constants", true])]
    [InlineData(
        data: ["React/System.Text.Json/services/_AutogeneratedServices.tst", "react-system-text-json/services", false])]
    [InlineData(
        data: ["React/System.Text.Json/models/_AutogeneratedModels.tst", "react-system-text-json/models", false])]
    [InlineData(
        data: ["React/Newtonsoft.Json/models/_AutogeneratedModels.tst", "react-newtonsoft-json/models", false])]
    public async Task GenerateAsyncMatchesExternalRecipeSnapshot(
        string recipeRelativePath,
        string snapshotDirectoryRelativePath,
        bool includeStaticConstants)
    {
        var repositoryRoot = FindRepositoryRoot();
        var recipePath = ResolveExternalRecipePath(repositoryRoot: repositoryRoot, relativePath: recipeRelativePath);
        if (!File.Exists(path: recipePath))
        {
            return;
        }

        var workspace = CreateWorkspaceDirectory();
        try
        {
            await WriteRecipeSampleProjectAsync(workspace: workspace, includeStaticConstants: includeStaticConstants);
            var templatePath = Path.Combine(path1: workspace, path2: "Recipe.tst");
#pragma warning disable SEC0116
            File.Copy(sourceFileName: recipePath, destFileName: templatePath, overwrite: true);
#pragma warning restore SEC0116

            var generator = new TypewriterGenerator(
                templateDiscovery: new FileSystemTemplateDiscovery(),
                metadataProvider: new CSharpProjectMetadataProvider(),
                fileWriter: new FileSystemGeneratedFileWriter());
            var configuration = TypewriterConfiguration.Default with
            {
                Output = TypewriterConfiguration.Default.Output with
                {
                    DryRun = true,
                    Newline = "lf",
                },
            };

            var result = await generator.GenerateAsync(
                request: new GenerationRequest(
                    WorkspacePath: workspace,
                    ProjectPath: Path.Combine(path1: workspace, path2: "RecipeSnapshotProject.csproj"),
                    TemplatePath: templatePath,
                    Mode: GenerationMode.Generate,
                    Configuration: configuration),
                cancellationToken: CancellationToken.None);

            result.Success.Should().BeTrue(because: FormatDiagnostics(diagnostics: result.Diagnostics));
            result.GeneratedFiles.Should().NotBeEmpty();

            var actualFiles = new Dictionary<string, string>(comparer: StringComparer.Ordinal);
            foreach (var generatedFile in result.GeneratedFiles)
            {
                Path.GetDirectoryName(path: generatedFile.Path).Should().Be(workspace);
                generatedFile.Content.Should().NotContain("\r\n");
                var fileName = Path.GetFileName(path: generatedFile.Path);
                actualFiles.Should().NotContainKey(fileName, because: $"Duplicate generated file name: {fileName}");
                actualFiles.Add(key: fileName, value: generatedFile.Content);
            }

            var snapshotDirectory = Path.Combine(
                repositoryRoot,
                "tests",
                "unit",
                "Typewriter.SnapshotTests",
                "ExternalRecipeSnapshots",
                NormalizePath(relativePath: snapshotDirectoryRelativePath));
            if (ShouldAcceptSnapshots())
            {
                if (Directory.Exists(path: snapshotDirectory))
                {
                    Directory.Delete(path: snapshotDirectory, recursive: true);
                }

                Directory.CreateDirectory(path: snapshotDirectory);
                foreach (var (fileName, content) in actualFiles)
                {
                    await File.WriteAllTextAsync(
                        path: Path.Combine(path1: snapshotDirectory, path2: fileName),
                        contents: content);
                }
            }

            Directory.Exists(path: snapshotDirectory).Should().BeTrue(because: $"Snapshot directory does not exist: {snapshotDirectory}");
            var expectedFiles = new Dictionary<string, string>(comparer: StringComparer.Ordinal);
            foreach (var expectedPath in Directory.GetFiles(path: snapshotDirectory))
            {
                expectedFiles.Add(
                    key: Path.GetFileName(path: expectedPath),
                    value: await File.ReadAllTextAsync(path: expectedPath));
            }

            actualFiles.Keys.Order(comparer: StringComparer.Ordinal).Should().Equal(expectedFiles.Keys.Order(comparer: StringComparer.Ordinal));
            foreach (var (fileName, expectedContent) in expectedFiles)
            {
                NormalizeLineEndings(value: actualFiles[key: fileName]).Should().Be(NormalizeLineEndings(value: expectedContent));
            }
        }
        finally
        {
            await DeleteDirectoryWithRetryAsync(directory: workspace);
        }
    }

    private static async Task WriteRecipeSampleProjectAsync(
        string workspace,
        bool includeStaticConstants)
    {
        Directory.CreateDirectory(path: Path.Combine(path1: workspace, path2: "Infrastructure"));
        Directory.CreateDirectory(path: Path.Combine(path1: workspace, path2: "Angular", path3: "Controllers"));
        Directory.CreateDirectory(path: Path.Combine(path1: workspace, path2: "Angular", path3: "Models"));
        Directory.CreateDirectory(path: Path.Combine(path1: workspace, path2: "React", path3: "Controllers"));
        Directory.CreateDirectory(path: Path.Combine(path1: workspace, path2: "React", path3: "Models"));

        await File.WriteAllTextAsync(
            path: Path.Combine(path1: workspace, path2: "RecipeSnapshotProject.csproj"),
            contents: """
                      <Project Sdk="Microsoft.NET.Sdk">
                        <PropertyGroup>
                          <TargetFramework>net10.0</TargetFramework>
                          <ImplicitUsings>enable</ImplicitUsings>
                          <Nullable>enable</Nullable>
                        </PropertyGroup>
                      </Project>
                      """).ConfigureAwait(continueOnCapturedContext: false);
        await File.WriteAllTextAsync(
            path: Path.Combine(path1: workspace, path2: "Infrastructure", path3: "Attributes.cs"),
            contents: """
                      namespace RecipeSnapshotProject.Infrastructure;

                      public abstract class ControllerBase
                      {
                      }

                      [AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface | AttributeTargets.Enum | AttributeTargets.Method)]
                      public sealed class GenerateFrontendTypeAttribute : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
                      public sealed class RouteAttribute(string template) : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Method)]
                      public sealed class HttpGetAttribute(string template) : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Method)]
                      public sealed class HttpPostAttribute(string template) : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Method)]
                      public sealed class ProducesResponseTypeAttribute(Type type, int statusCode) : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Parameter)]
                      public sealed class FromBodyAttribute : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Parameter)]
                      public sealed class FromRouteAttribute : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Property)]
                      public sealed class JsonIgnoreAttribute : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Property)]
                      public sealed class JsonPropertyNameAttribute(string name) : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Property)]
                      public sealed class JsonPropertyAttribute : Attribute
                      {
                          public JsonPropertyAttribute()
                          {
                          }

                          public JsonPropertyAttribute(string propertyName)
                          {
                          }

                          public string? PropertyName { get; init; }
                      }

                      [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
                      public sealed class JsonDerivedTypeAttribute : Attribute
                      {
                          public JsonDerivedTypeAttribute(Type derivedType, string typeDiscriminator)
                          {
                          }

                          public JsonDerivedTypeAttribute(Type derivedType, int typeDiscriminator)
                          {
                          }
                      }

                      [AttributeUsage(AttributeTargets.Class)]
                      public sealed class JsonPolymorphicAttribute : Attribute
                      {
                          public string? TypeDiscriminatorPropertyName { get; init; }
                      }

                      [AttributeUsage(AttributeTargets.Enum)]
                      public sealed class AsStringAttribute : Attribute
                      {
                      }

                      [AttributeUsage(AttributeTargets.Field)]
                      public sealed class LabelForEnumAttribute(string label) : Attribute
                      {
                      }
                      """).ConfigureAwait(continueOnCapturedContext: false);
        await WriteApiSampleAsync(
            workspace: workspace,
            folder: "Angular",
            rootNamespace: "AngularWebApiSample",
            includeStaticConstants: includeStaticConstants).ConfigureAwait(continueOnCapturedContext: false);
        await WriteApiSampleAsync(
            workspace: workspace,
            folder: "React",
            rootNamespace: "ReactWebApiSample",
            includeStaticConstants: includeStaticConstants).ConfigureAwait(continueOnCapturedContext: false);
    }

    private static async Task WriteApiSampleAsync(
        string workspace,
        string folder,
        string rootNamespace,
        bool includeStaticConstants)
    {
        await File.WriteAllTextAsync(
            path: Path.Combine(path1: workspace, path2: folder, path3: "Models", path4: "UserDto.cs"),
            contents: string.Create(
                provider: CultureInfo.InvariantCulture,
                handler: $$"""
                           using System;
                           using System.Collections.Generic;
                           using RecipeSnapshotProject.Infrastructure;

                           namespace {{rootNamespace}}.Models;

                           [GenerateFrontendType]
                           public class UserDto : NamedEntity
                           {
                               [JsonPropertyName("id")]
                               public required string Id { get; init; }

                               [JsonProperty(PropertyName = "displayName")]
                               public required string DisplayName { get; init; }

                               public UserStatus Status { get; init; }

                               public AddressDto? Address { get; init; }

                               public IReadOnlyList<string> Tags { get; init; } = [];

                               public Guid ExternalId { get; init; }

                               [JsonIgnore]
                               public string? InternalNotes { get; init; }
                           }

                           [GenerateFrontendType]
                           [JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
                           [JsonDerivedType(typeof(UserDto), "user")]
                           [JsonDerivedType(typeof(AdminUserDto), "admin")]
                           public abstract class NamedEntity
                           {
                               public required string Name { get; init; }
                           }

                           [GenerateFrontendType]
                           public sealed class AdminUserDto : UserDto
                           {
                               public required string Role { get; init; }
                           }

                           [GenerateFrontendType]
                           public sealed class AddressDto
                           {
                               public required string City { get; init; }
                           }
                           """)).ConfigureAwait(continueOnCapturedContext: false);
        await File.WriteAllTextAsync(
            path: Path.Combine(path1: workspace, path2: folder, path3: "Models", path4: "CreateUserRequest.cs"),
            contents: string.Create(
                provider: CultureInfo.InvariantCulture,
                handler: $$"""
                           using RecipeSnapshotProject.Infrastructure;

                           namespace {{rootNamespace}}.Models;

                           [GenerateFrontendType]
                           public sealed class CreateUserRequest
                           {
                               public required string DisplayName { get; init; }

                               public UserStatus Status { get; init; }
                           }
                           """)).ConfigureAwait(continueOnCapturedContext: false);
        await File.WriteAllTextAsync(
            path: Path.Combine(path1: workspace, path2: folder, path3: "Models", path4: "AuditInfo.cs"),
            contents: string.Create(
                provider: CultureInfo.InvariantCulture,
                handler: $$"""
                           using System;
                           using RecipeSnapshotProject.Infrastructure;

                           namespace {{rootNamespace}}.Models;

                           [GenerateFrontendType]
                           public sealed record AuditInfo(string CreatedBy, DateTime CreatedAt);
                           """)).ConfigureAwait(continueOnCapturedContext: false);
        await File.WriteAllTextAsync(
            path: Path.Combine(path1: workspace, path2: folder, path3: "Models", path4: "UserStatus.cs"),
            contents: string.Create(
                provider: CultureInfo.InvariantCulture,
                handler: $$"""
                           using RecipeSnapshotProject.Infrastructure;

                           namespace {{rootNamespace}}.Models;

                           [GenerateFrontendType]
                           [AsString]
                           public enum UserStatus
                           {
                               [LabelForEnum("Active user")]
                               Active = 1,
                               Disabled = 2,
                           }
                           """)).ConfigureAwait(continueOnCapturedContext: false);
        if (includeStaticConstants)
        {
            Directory.CreateDirectory(path: Path.Combine(path1: workspace, path2: folder, path3: "Constants"));
            await File.WriteAllTextAsync(
                path: Path.Combine(path1: workspace, path2: folder, path3: "Constants", path4: "ApiConstants.cs"),
                contents: string.Create(
                    provider: CultureInfo.InvariantCulture,
                    handler: $$"""
                               using RecipeSnapshotProject.Infrastructure;

                               namespace {{rootNamespace}}.Constants;

                               [GenerateFrontendType]
                               public static class ApiConstants
                               {
                                   public const string DefaultCulture = "en-US";

                                   public const string HubPath = "hubs/chat";
                               }
                               """)).ConfigureAwait(continueOnCapturedContext: false);
        }

        await File.WriteAllTextAsync(
            path: Path.Combine(path1: workspace, path2: folder, path3: "Controllers", path4: "UsersController.cs"),
            contents: string.Create(
                provider: CultureInfo.InvariantCulture,
                handler: $$"""
                           using System.Threading;
                           using System.Threading.Tasks;
                           using {{rootNamespace}}.Models;
                           using RecipeSnapshotProject.Infrastructure;

                           namespace {{rootNamespace}}.Controllers;

                           [GenerateFrontendType]
                           [Route("api/[controller]")]
                           public sealed class UsersController : ControllerBase
                           {
                               [HttpGet("items/{id}")]
                               [ProducesResponseType(typeof(UserDto), 200)]
                               public Task<UserDto> GetItemAsync([FromRoute] int id, string? search = null)
                               {
                                   throw new NotImplementedException();
                               }

                               [HttpPost("items")]
                               [ProducesResponseType(typeof(UserDto), 201)]
                               public Task<UserDto> CreateAsync([FromBody] CreateUserRequest request, CancellationToken cancellationToken)
                               {
                                   throw new NotImplementedException();
                               }
                           }
                           """)).ConfigureAwait(continueOnCapturedContext: false);
    }

    private static string ResolveExternalRecipePath(
        string repositoryRoot,
        string relativePath)
    {
        var gitHubRoot = Directory.GetParent(path: repositoryRoot)?.FullName ?? repositoryRoot;
        return Path.Combine(
            paths: [gitHubRoot, "NetCoreTypewriterRecipes", .. relativePath.Split(separator: '/')]);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(path: AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(path: Path.Combine(path1: directory.FullName, path2: "AdaskoTheBeAsT.Typewriter.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        return AppContext.BaseDirectory;
    }

    private static string CreateWorkspaceDirectory()
    {
        var directory = Path.Combine(
            path1: Path.GetTempPath(),
            path2: "Typewriter.SnapshotTests",
            path3: Guid.NewGuid().ToString(format: "N"));
        Directory.CreateDirectory(path: directory);
        return directory;
    }

    private static async Task DeleteDirectoryWithRetryAsync(string directory)
    {
        const int MaxAttempts = 10;

        for (var attempt = 1; attempt <= MaxAttempts; attempt++)
        {
            try
            {
                if (Directory.Exists(path: directory))
                {
                    Directory.Delete(path: directory, recursive: true);
                }

                return;
            }
            catch (IOException) when (attempt < MaxAttempts)
            {
                await Task.Delay(millisecondsDelay: 100).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch (UnauthorizedAccessException) when (attempt < MaxAttempts)
            {
                await Task.Delay(millisecondsDelay: 100).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
    }

    private static string NormalizePath(string relativePath) =>
        Path.Combine(paths: relativePath.Split(separator: '/'));

    private static bool ShouldAcceptSnapshots() =>
        string.Equals(
            a: Environment.GetEnvironmentVariable(variable: "TYPEWRITER_ACCEPT_EXTERNAL_RECIPE_SNAPSHOTS"),
            b: "1",
            comparisonType: StringComparison.Ordinal);

    private static string NormalizeLineEndings(string value) =>
        value.Replace(oldValue: "\r\n", newValue: "\n", comparisonType: StringComparison.Ordinal)
            .Replace(oldChar: '\r', newChar: '\n');

    private static string FormatDiagnostics(IEnumerable<GenerationDiagnostic> diagnostics) =>
        string.Join(
            separator: Environment.NewLine,
            values: diagnostics.Select(
                selector: diagnostic =>
                    string.Create(
                        provider: CultureInfo.InvariantCulture,
                        handler: $"{diagnostic.Severity}: {diagnostic.Code} {diagnostic.Message} {diagnostic.File}:{diagnostic.Line}:{diagnostic.Column}")));
}
