// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.
import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import {
  withTypewriterRequestSchema,
  withTypewriterResponseSchema
} from '@adaskothebeast/typewriter-http-angular';


import { Observable } from 'rxjs';

import { API_BASE_URL } from '../../app/app-config.module';
import { apiTypeRegistry } from '../models/typewriter-registry';


import { HttpParamsProcessorService } from '@adaskothebeast/http-params-processor';
import { UserDto } from '../models/UserDto';
import { CreateUserRequest } from '../models/CreateUserRequest';

import { CreateUserRequestSchema } from '../models/CreateUserRequest.schema';
import { UserDtoSchema } from '../models/UserDto.schema';


interface Object {
  hasOwnProperty<TK extends string>(v: TK): this is Record<TK, object>;
}

export interface IApiUsersService {
    getItemAsyncnumberstring(id: number, search: string): Observable<UserDto>;
    createAsyncCreateUserRequest(request: CreateUserRequest): Observable<UserDto>;
}

@Injectable(
    { providedIn: 'root' }
)
export class ApiUsersService implements IApiUsersService {
    constructor (
      @Inject(HttpClient) protected http: HttpClient,
      @Inject(HttpParamsProcessorService) protected processor: HttpParamsProcessorService,
      @Optional() @Inject(API_BASE_URL) protected baseUrl?: string) {
    }

    public get usersServiceUrl(): string {
        if (this.baseUrl) {
            return this.baseUrl.endsWith('/') ? this.baseUrl + 'api/Users' : this.baseUrl + '/' + 'api/Users';
        } else {
            return 'api/Users';
        }
    }

    public getItemAsyncnumberstring(id: number, search: string): Observable<UserDto> {
        const headers = new HttpHeaders()
            .set('Accept', 'application/json')
            .set('If-Modified-Since', '0');

        let params = new HttpParams();

        const parr = [];

        parr.push(id);
        params = this.processor.processWithParams(params, 'id', parr.pop());
        parr.push(search);
        params = this.processor.processWithParams(params, 'search', parr.pop());

        return this.http.get<UserDto>(
            this.usersServiceUrl + '/items/{id}',
            {
                context: withTypewriterResponseSchema(UserDtoSchema, { registry: apiTypeRegistry }),
                headers,
                params
            });
    }









    public createAsyncCreateUserRequest(request: CreateUserRequest): Observable<UserDto> {
        const headers = new HttpHeaders()
            .set('Content-Type', 'application/json')
            .set('Accept', 'application/json')
            .set('If-Modified-Since', '0');

        return this.http.post<UserDto>(
            this.usersServiceUrl + '/items',
            request,
            {
                context: withTypewriterResponseSchema(UserDtoSchema, { context: withTypewriterRequestSchema(CreateUserRequestSchema, { registry: apiTypeRegistry }), registry: apiTypeRegistry }),
                headers
            });
    }
}
