// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

export interface IAuditInfo {
  createdBy?: string;
  createdAt?: Date;
}

export class AuditInfo implements IAuditInfo {
  public createdBy: string;
  public createdAt: Date;

  constructor(initObj?: IAuditInfo) {
    if (initObj) {
      this.createdBy = initObj.createdBy ?? '';
      this.createdAt = initObj.createdAt ?? new Date();
    } else {
      this.createdBy = '';
      this.createdAt = new Date();
    }
  }
}
