// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

import { UserStatus } from './UserStatus';

export interface ICreateUserRequest {
  displayName?: string;
  status?: UserStatus;
}

export class CreateUserRequest implements ICreateUserRequest {
  public displayName: string;
  public status: UserStatus;

  constructor(initObj?: ICreateUserRequest) {
    if (initObj) {
      this.displayName = initObj.displayName ?? '';
      this.status = initObj.status ?? UserStatus.Active;
    } else {
      this.displayName = '';
      this.status = UserStatus.Active;
    }
  }
}

