// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

export class Model {
    value: Box<number>;
    boxes: Box<number>[];
    boxByName: Record<string, Box<number>>;
}

