// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.





export interface IAuditInfo {
  createdBy?: string;
  createdAt?: string;
}

export class AuditInfo implements IAuditInfo {
  public createdBy: string;
  public createdAt: string;

  constructor(initObj?: IAuditInfo) {
    if (initObj) {
      this.createdBy = initObj.createdBy ?? '';
      this.createdAt = initObj.createdAt ?? new Date();
    } else {
      this.createdBy = '';
      this.createdAt = new Date();
    }
  }
}

