// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.



import { Temporal } from '@js-temporal/polyfill';

export interface IAuditInfo {
  createdBy?: string;
  createdAt?: Temporal.PlainDateTime;
}

export class AuditInfo implements IAuditInfo {
  public createdBy: string;
  public createdAt: Temporal.PlainDateTime;

  constructor(initObj?: IAuditInfo) {
    if (initObj) {
      this.createdBy = initObj.createdBy ?? '';
      this.createdAt = initObj.createdAt ?? Temporal.Now.plainDateTimeISO();
    } else {
      this.createdBy = '';
      this.createdAt = Temporal.Now.plainDateTimeISO();
    }
  }
}

