// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

/* eslint-disable @typescript-eslint/no-explicit-any */

export const DEFAULTCULTURE: string = 'en-US';
export const HUBPATH: string = 'hubs/chat';

