// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

import { environment } from '../../environments/environment';

import * as qs from 'qs';
import { UserDto } from '../models/UserDto';
import { CreateUserRequest } from '../models/CreateUserRequest';


const getUrl = () => {
  if(environment.apiBaseUrl) {
    return environment.apiBaseUrl.endsWith('/') ?
      `${environment.apiBaseUrl}api/Users` :
      `${environment.apiBaseUrl}/api/Users`;
  }

  return 'api/Users';
}; 

const usersServiceUrl = getUrl();

export const usersApi = createApi({
  reducerPath: 'usersApi',
  baseQuery: fetchBaseQuery({ baseUrl: environment.apiBaseUrl }),
  endpoints: (builder) => ({
    getItemAsyncnumberstring: builder.query<UserDto, number, string>({
      query: (id, search) => {
        const paramObj = {
          id: id, search: search
        };
        const queryPath = qs.stringify(paramObj);
        const url = usersServiceUrl + '?' + queryPath;
        
        

        return {
          url: url,
          method: 'GET',
          headers: {
            'Accept': 'application/json',
            'If-Modified-Since': '0',
          }
        };
      },
    }),
  
  
  
  
  
  
  
  
  
  
  
    createAsyncCreateUserRequest: builder.mutation<UserDto, CreateUserRequest>({
      query: (request) => {
        const body=request;
        
        
        return {
          url: usersServiceUrl,
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'If-Modified-Since': '0',
          },
          body: body
        };
      },
    }),
  })
});    

export const {
  useGetItemAsyncnumberstringQuery,
  useCreateAsyncCreateUserRequestMutation
} = usersApi;

