using System.Diagnostics.CodeAnalysis;

namespace AdaskoTheBeAsT.Typewriter.Annotations;

/// <summary>
/// Marks a class, interface, enum, or method so that Typewriter templates
/// include it in frontend code generation. When applied without a
/// <c>dllName</c> the type is generated by the template that
/// matches its kind; when a <c>dllName</c> is supplied the
/// template can use it to route the type to a specific output assembly.
/// </summary>
/// <remarks>
/// Typewriter recognises this attribute by simple name, so user-defined
/// attributes named <c>GenerateFrontendTypeAttribute</c> in any namespace
/// continue to work without referencing this package.
/// </remarks>
[AttributeUsage(
    AttributeTargets.Class | AttributeTargets.Enum | AttributeTargets.Interface | AttributeTargets.Method,
    Inherited = false)]
[ExcludeFromCodeCoverage]
public sealed class GenerateFrontendTypeAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="GenerateFrontendTypeAttribute"/> class.
    /// </summary>
    public GenerateFrontendTypeAttribute()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GenerateFrontendTypeAttribute"/> class
    /// with the specified DLL name.
    /// </summary>
    /// <param name="dllName">The name of the output assembly the type should be routed to.</param>
    public GenerateFrontendTypeAttribute(string dllName)
    {
        DllName = dllName;
    }

    /// <summary>
    /// Gets the name of the output assembly the type should be routed to,
    /// or <see langword="null"/> when no specific routing is required.
    /// </summary>
    public string? DllName { get; }
}
