// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.





export interface IAuditInfo {
  $type?: string;
  createdBy?: string;
  createdAt?: Date;
}

export class AuditInfo implements IAuditInfo {
  public $type: string;
  public createdBy: string;
  public createdAt: Date;

  constructor(initObj?: IAuditInfo) {
    this.$type = 'AngularWebApiSample.Models.AuditInfo,'
            + 'AngularWebApiSample.Models';
    if (initObj) {
      this.createdBy = initObj.createdBy ?? '';
      this.createdAt = initObj.createdAt ?? new Date();
    } else {
      this.createdBy = '';
      this.createdAt = new Date();
    }
  }
}

