// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

/* eslint-disable @typescript-eslint/no-explicit-any */







export interface IAuditInfo {
  createdBy?: string;
  createdAt?: Date;
}

export class AuditInfo implements IAuditInfo {
  public $type: string;
  public createdBy: string;
  public createdAt: Date;

  constructor(initObj?: IAuditInfo) {
    this.$type = 'AngularWebApiSample.Models.AuditInfo,'
            + 'RecipeSnapshotProject';
    if (initObj) {
      this.createdBy = initObj.createdBy ?? '';
      this.createdAt = initObj.createdAt ?? new Date();
    } else {
      this.createdBy = '';
      this.createdAt = new Date();
    }
  }
}

