// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

/* eslint-disable @typescript-eslint/no-explicit-any */





import { Temporal } from '@js-temporal/polyfill';

export interface IAuditInfo {
  createdBy?: string;
  createdAt?: Temporal.PlainDateTime;
}

export class AuditInfo implements IAuditInfo {
  public $type: string;
  public createdBy: string;
  public createdAt: Temporal.PlainDateTime;

  constructor(initObj?: IAuditInfo) {
    this.$type = 'AngularWebApiSample.Models.AuditInfo,'
            + 'RecipeSnapshotProject';
    if (initObj) {
      this.createdBy = initObj.createdBy ?? '';
      this.createdAt = initObj.createdAt ?? Temporal.Now.plainDateTimeISO();
    } else {
      this.createdBy = '';
      this.createdAt = Temporal.Now.plainDateTimeISO();
    }
  }
}

