// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.


import { UserStatus } from './UserStatus';

export interface ICreateUserRequest {
  $type?: string;
  displayName?: string;
  status?: UserStatus;
}

export class CreateUserRequest implements ICreateUserRequest {
  public $type: string;
  public displayName: string;
  public status: UserStatus;

  constructor(initObj?: ICreateUserRequest) {
    this.$type = 'AngularWebApiSample.Models.CreateUserRequest,'
            + 'AngularWebApiSample.Models';
    if (initObj) {
      this.displayName = initObj.displayName ?? '';
      this.status = initObj.status ?? UserStatus.Active;
    } else {
      this.displayName = '';
      this.status = UserStatus.Active;
    }
  }
}


