// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

/* eslint-disable @typescript-eslint/no-explicit-any */



import { UserStatus } from './UserStatus';

export interface ICreateUserRequest {
  displayName?: string;
  status?: UserStatus;
}

export class CreateUserRequest implements ICreateUserRequest {
  public $type: string;
  public displayName: string;
  public status: UserStatus;

  constructor(initObj?: ICreateUserRequest) {
    this.$type = 'AngularWebApiSample.Models.CreateUserRequest,'
            + 'RecipeSnapshotProject';
    if (initObj) {
      this.displayName = initObj.displayName ?? '';
      this.status = initObj.status ?? UserStatus.Active;
    } else {
      this.displayName = '';
      this.status = UserStatus.Active;
    }
  }
}



