// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.


import { UserStatus } from './UserStatus';
import { AddressDto } from './AddressDto';
import { INamedEntity, NamedEntity } from './NamedEntity';

export interface IUserDto extends INamedEntity {
  id?: string;
  displayName?: string;
  status?: UserStatus;
  address?: AddressDto | null;
  tags?: string[];
  externalId?: string;
}

export class UserDto extends NamedEntity implements IUserDto {
  public id: string;
  public displayName: string;
  public status: UserStatus;
  public address?: AddressDto | null;
  public tags: string[];
  public externalId: string;

  constructor(initObj?: IUserDto) {
    super(initObj);
    this.$type = 'AngularWebApiSample.Models.UserDto,'
            + 'AngularWebApiSample.Models';
    if (initObj) {
      this.id = initObj.id ?? '';
      this.displayName = initObj.displayName ?? '';
      this.status = initObj.status ?? UserStatus.Active;
      this.address = initObj.address ?? null;
      this.tags = initObj.tags ?? [];
      this.externalId = initObj.externalId ?? '00000000-0000-0000-0000-000000000000';
    } else {
      this.id = '';
      this.displayName = '';
      this.status = UserStatus.Active;
      this.address = null;
      this.tags = [];
      this.externalId = '00000000-0000-0000-0000-000000000000';
    }
  }
}


export interface INamedEntity {
  $type?: string;
  name?: string;
}

export class NamedEntity implements INamedEntity {
  public $type: string;
  public name: string;

  constructor(initObj?: INamedEntity) {
    this.$type = 'AngularWebApiSample.Models.NamedEntity,'
            + 'AngularWebApiSample.Models';
    if (initObj) {
      this.name = initObj.name ?? '';
    } else {
      this.name = '';
    }
  }
}
import { IUserDto, UserDto } from './UserDto';

export interface IAdminUserDto extends IUserDto {
  role?: string;
}

export class AdminUserDto extends UserDto implements IAdminUserDto {
  public role: string;

  constructor(initObj?: IAdminUserDto) {
    super(initObj);
    this.$type = 'AngularWebApiSample.Models.AdminUserDto,'
            + 'AngularWebApiSample.Models';
    if (initObj) {
      this.role = initObj.role ?? '';
    } else {
      this.role = '';
    }
  }
}


export interface IAddressDto {
  $type?: string;
  city?: string;
}

export class AddressDto implements IAddressDto {
  public $type: string;
  public city: string;

  constructor(initObj?: IAddressDto) {
    this.$type = 'AngularWebApiSample.Models.AddressDto,'
            + 'AngularWebApiSample.Models';
    if (initObj) {
      this.city = initObj.city ?? '';
    } else {
      this.city = '';
    }
  }
}


