// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

/* eslint-disable @typescript-eslint/no-explicit-any */

export enum UserStatus {
  Active = 'Active',

  Disabled = 'Disabled'
}

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace UserStatus {
  export function getLabel(value: UserStatus): string {
    let toReturn = '';
    switch(value) {
      case UserStatus.Active:
        toReturn = 'Active user';
        break;
      case UserStatus.Disabled:
        toReturn = 'Disabled';
        break;
    }
    return toReturn;
  }
}






