namespace Typewriter.Engine;

public static class GeneratedFileHeader
{
    public const string Value =
        """
        // <auto-generated />
        // This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
        // https://github.com/AdaskoTheBeAsT/Typewriter
        """;
}
