namespace Typewriter.Engine;

public static class GeneratedFileHeader
{
    public const string Value =
        "// <auto-generated />\n"
        + "// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.\n"
        + "// https://github.com/AdaskoTheBeAsT/Typewriter";
}
