using System.Diagnostics;
using Typewriter.Abstractions;

namespace Typewriter.Engine;

public sealed class TypewriterGenerator : ITypewriterGenerator
{
    private readonly IGeneratedFileWriter _fileWriter;
    private readonly IProjectMetadataProvider _metadataProvider;
    private readonly GeneratedFilePlanner _planner;
    private readonly ITemplateDiscovery _templateDiscovery;
    private readonly TemplateRenderer _templateRenderer;

    public TypewriterGenerator(
        ITemplateDiscovery templateDiscovery,
        IProjectMetadataProvider metadataProvider,
        IGeneratedFileWriter fileWriter)
        : this(
            templateDiscovery: templateDiscovery,
            metadataProvider: metadataProvider,
            fileWriter: fileWriter,
            templateRenderer: new TemplateRenderer(typeMapper: new TypeScriptTypeMapper()),
            planner: new GeneratedFilePlanner())
    {
    }

    public TypewriterGenerator(
        ITemplateDiscovery templateDiscovery,
        IProjectMetadataProvider metadataProvider,
        IGeneratedFileWriter fileWriter,
        TemplateRenderer templateRenderer,
        GeneratedFilePlanner planner)
    {
        _templateDiscovery = templateDiscovery;
        _metadataProvider = metadataProvider;
        _fileWriter = fileWriter;
        _templateRenderer = templateRenderer;
        _planner = planner;
    }

    public async Task<GenerationResult> GenerateAsync(
        GenerationRequest request,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(argument: request);

        var stopwatch = Stopwatch.StartNew();
        var diagnostics = new List<GenerationDiagnostic>();
        var generatedFiles = new List<GeneratedFile>();
        var plannedOutputPaths = new Dictionary<string, string>(comparer: StringComparer.OrdinalIgnoreCase);

        var workspace = new WorkspaceContext(RootPath: WorkspaceProjectResolver.ResolveWorkspacePath(request: request));
        var projectPaths = WorkspaceProjectResolver.ResolveProjectPaths(request: request, workspacePath: workspace.RootPath, diagnostics: diagnostics);
        if (projectPaths.Count == 0)
        {
            return CreateResult(stopwatch: stopwatch, generatedFiles: generatedFiles, diagnostics: diagnostics, request: request);
        }

        var renderDefaults = TemplateRenderDefaults.FromConfiguration(
            configuration: request.Configuration,
            solutionFullName: ResolveSolutionFullName(workspaceRootPath: workspace.RootPath));
        foreach (var projectPath in projectPaths)
        {
            cancellationToken.ThrowIfCancellationRequested();
            await GenerateProjectAsync(
                request: request,
                workspace: workspace,
                templateWorkspace: CreateProjectWorkspace(request: request, workspace: workspace, projectPath: projectPath, projectCount: projectPaths.Count),
                projectPath: projectPath,
                renderDefaults: renderDefaults,
                diagnostics: diagnostics,
                generatedFiles: generatedFiles,
                plannedOutputPaths: plannedOutputPaths,
                cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }

        return CreateResult(stopwatch: stopwatch, generatedFiles: generatedFiles, diagnostics: diagnostics, request: request);
    }

    private static void ReportDuplicateOutputPath(
        TemplateDocument template,
        GeneratedFile plannedFile,
        ICollection<GenerationDiagnostic> diagnostics,
        IDictionary<string, string> plannedOutputPaths)
    {
        var normalizedPath = Path.GetFullPath(path: plannedFile.Path);
        if (!plannedOutputPaths.TryGetValue(key: normalizedPath, value: out var firstTemplatePath))
        {
            plannedOutputPaths[key: normalizedPath] = template.Path;
            return;
        }

        var message = string.Equals(a: firstTemplatePath, b: template.Path, comparisonType: StringComparison.OrdinalIgnoreCase)
            ? $"Template '{template.Path}' generates the output file '{normalizedPath}' more than once. The last render wins."
            : $"Output file '{normalizedPath}' is generated by more than one template: '{firstTemplatePath}' and '{template.Path}'. The last render wins.";
        diagnostics.Add(
            item: new GenerationDiagnostic(
                File: template.Path,
                Line: null,
                Column: null,
                Severity: DiagnosticSeverity.Warning,
                Message: message,
                Code: DiagnosticCodes.DuplicateGeneratedOutput));
    }

    private static bool ShouldRenderPerSourceFile(
        TemplateDocument template,
        ProjectMetadata project,
        TemplateRenderResult renderResult)
    {
        return template.OutputPath is null
            && !renderResult.IsSingleFileMode
            && (renderResult.OutputPath is null || renderResult.UsesOutputFilenameFactory)
            && project.SourceFiles.Any(predicate: sourceFile => sourceFile.Types.Count > 0);
    }

    private static TemplateRenderResult ApplyLegacySourceOutputPath(
        SourceFileMetadata sourceFile,
        TemplateRenderResult renderResult,
        FileNameConvention fileNameConvention)
    {
        if (!string.IsNullOrWhiteSpace(value: renderResult.OutputPath))
        {
            return renderResult;
        }

        var outputFileName = FileNameConventionFormatter.Format(
            value: Path.GetFileNameWithoutExtension(path: sourceFile.Path),
            convention: fileNameConvention)
            + NormalizeOutputExtension(outputExtension: renderResult.OutputExtension);
        var outputPath = string.IsNullOrWhiteSpace(value: renderResult.OutputDirectory)
            ? outputFileName
            : Path.Combine(path1: renderResult.OutputDirectory, path2: outputFileName);

        return renderResult with { OutputPath = outputPath };
    }

    private static string NormalizeOutputExtension(string? outputExtension)
    {
        if (string.IsNullOrWhiteSpace(value: outputExtension))
        {
            return ".ts";
        }

        return outputExtension.StartsWith(value: '.')
            ? outputExtension
            : "." + outputExtension;
    }

    private static ProjectMetadata CreateSourceFileProject(
        ProjectMetadata project,
        SourceFileMetadata sourceFile)
    {
        return new ProjectMetadata(
            ProjectPath: project.ProjectPath,
            SourceFiles: [sourceFile],
            Types: sourceFile.Types,
            Diagnostics: []);
    }

    private static string? ResolveSolutionFullName(string workspaceRootPath)
    {
        var fullPath = Path.GetFullPath(path: workspaceRootPath);
        var isSolutionFile = fullPath.EndsWith(value: ".sln", comparisonType: StringComparison.OrdinalIgnoreCase)
            || fullPath.EndsWith(value: ".slnx", comparisonType: StringComparison.OrdinalIgnoreCase);
        return isSolutionFile && File.Exists(path: fullPath)
            ? fullPath
            : null;
    }

    private static WorkspaceContext CreateProjectWorkspace(
        GenerationRequest request,
        WorkspaceContext workspace,
        string projectPath,
        int projectCount)
    {
        if (projectCount <= 1 || !string.IsNullOrWhiteSpace(value: request.TemplatePath))
        {
            return workspace;
        }

        return new WorkspaceContext(
            RootPath: Path.GetDirectoryName(path: Path.GetFullPath(path: projectPath))
                      ?? workspace.RootPath);
    }

    private static GenerationResult CreateResult(
        Stopwatch stopwatch,
        IReadOnlyList<GeneratedFile> generatedFiles,
        IReadOnlyList<GenerationDiagnostic> diagnostics,
        GenerationRequest request)
    {
        stopwatch.Stop();
        var hasErrors = diagnostics.Any(predicate: diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
        var hasFailedWarnings = request.Configuration.Diagnostics.FailOnWarning
            && diagnostics.Any(predicate: diagnostic => diagnostic.Severity == DiagnosticSeverity.Warning);

        return new GenerationResult(
            Success: !hasErrors && !hasFailedWarnings,
            GeneratedFiles: generatedFiles,
            Diagnostics: diagnostics,
            Duration: stopwatch.Elapsed);
    }

    private static CompiledTemplateFactory? CreateCompiledTemplateFactory(
        TemplateDocument template,
        ICollection<GenerationDiagnostic> diagnostics) =>
        template.CodeBlocks.Count == 0
            ? null
            : TemplateRuntimeCompiler.CompileFactory(template: template, diagnostics: diagnostics);

#pragma warning disable MA0051,S107,S3776
    private async Task GenerateProjectAsync(
        GenerationRequest request,
        WorkspaceContext workspace,
        WorkspaceContext templateWorkspace,
        string projectPath,
        TemplateRenderDefaults renderDefaults,
        ICollection<GenerationDiagnostic> diagnostics,
        ICollection<GeneratedFile> generatedFiles,
        IDictionary<string, string> plannedOutputPaths,
        CancellationToken cancellationToken)
#pragma warning restore MA0051,S107,S3776
    {
        var templates = await _templateDiscovery.FindTemplatesAsync(
            workspace: templateWorkspace,
            request: request,
            cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

        if (templates.Count == 0)
        {
            diagnostics.Add(
                item: new GenerationDiagnostic(
                    File: workspace.RootPath,
                    Line: null,
                    Column: null,
                    Severity: DiagnosticSeverity.Warning,
                    Message: $"No .tst templates were found for project: {projectPath}.",
                    Code: null));
            return;
        }

        var project = await _metadataProvider.GetMetadataAsync(
            project: new ProjectContext(
                ProjectPath: projectPath,
                WorkspacePath: workspace.RootPath,
                TargetFramework: request.Configuration.DefaultTargetFramework),
            cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        foreach (var diagnostic in project.Diagnostics)
        {
            diagnostics.Add(item: diagnostic);
        }

        if (project.Diagnostics.Any(predicate: diagnostic => diagnostic.Severity == DiagnosticSeverity.Error))
        {
            return;
        }

        foreach (var templateFile in templates)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var templateDiagnostics = new List<GenerationDiagnostic>();
            var template = TemplateDocument.Parse(template: templateFile, diagnostics: templateDiagnostics);
#pragma warning disable CA2000
            var compiledTemplateFactory = CreateCompiledTemplateFactory(template: template, diagnostics: templateDiagnostics);
#pragma warning restore CA2000
            try
            {
                if (templateDiagnostics.Any(predicate: diagnostic => diagnostic.Severity == DiagnosticSeverity.Error))
                {
                    foreach (var templateDiagnostic in templateDiagnostics)
                    {
                        diagnostics.Add(item: templateDiagnostic);
                    }

                    continue;
                }

                var renderResult = _templateRenderer.RenderTemplate(
                    template: template,
                    metadata: project,
                    diagnostics: templateDiagnostics,
                    defaults: renderDefaults,
                    compiledTemplateFactory: compiledTemplateFactory);
                if (ShouldRenderPerSourceFile(template: template, project: project, renderResult: renderResult))
                {
                    foreach (var sourceFile in project.SourceFiles.Where(predicate: sourceFile => sourceFile.Types.Count > 0))
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        var sourceProject = CreateSourceFileProject(project: project, sourceFile: sourceFile);
                        var sourceDiagnostics = new List<GenerationDiagnostic>();
                        var sourceRenderResult = _templateRenderer.RenderTemplate(
                            template: template,
                            metadata: sourceProject,
                            diagnostics: sourceDiagnostics,
                            defaults: renderDefaults,
                            compiledTemplateFactory: compiledTemplateFactory);
                        foreach (var sourceDiagnostic in sourceDiagnostics)
                        {
                            diagnostics.Add(item: sourceDiagnostic);
                        }

                        if (sourceDiagnostics.Any(predicate: diagnostic => diagnostic.Severity == DiagnosticSeverity.Error))
                        {
                            continue;
                        }

                        if (sourceRenderResult.RootItemCount == 0)
                        {
                            continue;
                        }

                        sourceRenderResult = ApplyLegacySourceOutputPath(
                            sourceFile: sourceFile,
                            renderResult: sourceRenderResult,
                            fileNameConvention: request.Configuration.Output.FileNameConvention);
                        await PlanAndWriteAsync(
                            request: request,
                            templateWorkspace: templateWorkspace,
                            template: template,
                            renderResult: sourceRenderResult,
                            diagnostics: diagnostics,
                            generatedFiles: generatedFiles,
                            plannedOutputPaths: plannedOutputPaths,
                            cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    }

                    continue;
                }

                foreach (var templateDiagnostic in templateDiagnostics)
                {
                    diagnostics.Add(item: templateDiagnostic);
                }

                await PlanAndWriteAsync(
                    request: request,
                    templateWorkspace: templateWorkspace,
                    template: template,
                    renderResult: renderResult,
                    diagnostics: diagnostics,
                    generatedFiles: generatedFiles,
                    plannedOutputPaths: plannedOutputPaths,
                    cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            finally
            {
                compiledTemplateFactory?.Dispose();
            }
        }
    }

#pragma warning disable S107
    private async Task PlanAndWriteAsync(
        GenerationRequest request,
        WorkspaceContext templateWorkspace,
        TemplateDocument template,
        TemplateRenderResult renderResult,
        ICollection<GenerationDiagnostic> diagnostics,
        ICollection<GeneratedFile> generatedFiles,
        IDictionary<string, string> plannedOutputPaths,
        CancellationToken cancellationToken)
#pragma warning restore S107
    {
        if (!_planner.TryPlan(
                workspace: templateWorkspace,
                template: template,
                outputPath: renderResult.OutputPath,
                content: renderResult.Content,
                fileNameConvention: request.Configuration.Output.FileNameConvention,
                utf8Bom: renderResult.Utf8Bom,
                generatedFile: out var plannedFile,
                diagnostic: out var diagnostic))
        {
            if (diagnostic is not null)
            {
                diagnostics.Add(item: diagnostic);
            }

            return;
        }

        if (plannedFile is not null)
        {
            ReportDuplicateOutputPath(template: template, plannedFile: plannedFile, diagnostics: diagnostics, plannedOutputPaths: plannedOutputPaths);
            var generatedFile = await _fileWriter.WriteAsync(
                file: plannedFile,
                request: request,
                cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            generatedFiles.Add(item: generatedFile);
        }
    }
}
