// <auto-generated />
// This file was generated by AdaskoTheBeAsT Typewriter. Do not edit manually.
// https://github.com/AdaskoTheBeAsT/Typewriter

export class SharedDto {
    public correlationId: string;
    public payload: string;
}

